name: 'Hola Mundo' 
description: 'Saludar'
inputs:
  who-to-greet:
    description: 'A quien saluda'
    required: true
    default: 'Mundo'
outputs:
  time:
    description:'Fecha en que nos conocimos'
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{inputs.who-to-greet}}